#!/bin/bash

FILE=$1

if [[ q$FILE == 'q' ]]
then
	echo "Usage: $0 <one filename in set>"
	exit 1
fi

MATCHSTR=`echo $FILE | sed '{s/\./ /g}' | awk '{print $(NF-1)}'`
MYPATH=`echo $FILE | sed '{s/a_10/ &/g}'| awk '{print $1}'`

echo $MATCHSTR
echo "Executing stopurms"
/home/sr99_ramp_metering/system/stopurms
sleep 1

echo "Executing stopreplay"
/home/sr99_ramp_metering/system/stopreplay
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/sr99_ramp_metering/src/lnx/clt_vars &
sleep 1

y=3000
for x in `ls $MYPATH/*$MATCHSTR.dat`
do
	/home/sr99_ramp_metering/system/replay_controller_go $y $x 1000
	y=$(($y+200))
done

echo "Starting opt_crm"
cd /home/sr99_ramp_metering/src
./lnx/opt_crm &

while [[ 1 ]] 
do
	ps -ef | grep replay_general | grep -v grep
	if [[ $? != 0 ]]
	then
		killall opt_crm
		exit 1
	fi
	sleep 1
done
