#!/bin/bash

echo "Stopping opt_crm"
sudo killall opt_crm
sleep 1

echo "Stopping replay_general"
sudo killall replay_general
sleep 1

echo "Stopping clt_vars"
sudo killall clt_vars
sleep 1

echo "Stopping db_slv"
sudo killall db_slv
sleep 1

/home/path/db/db_clean.sh
