#!/bin/bash

echo "Executing stopurms"
/home/sr99_ramp_metering/system/stopurms
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

#echo "Starting clt_vars"
#/home/sr99_ramp_metering/src/lnx/clt_vars &
#sleep 1

TIMESTAMP=`date +%y%m%d_%H%M%S`

/home/sr99_ramp_metering/system/urmsgo 10.29.248.108	3000	1000	$TIMESTAMP	2000
sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.25.113	3200	1000	$TIMESTAMP	2000
sleep 5
/home/sr99_ramp_metering/src/lnx/opt_crm -d
#/home/sr99_ramp_metering/src/lnx/opt_crm 1>>/big/data/ac_rm_1/opt_crm_$TIMESTAMP.log 2>&1 &
