#!/bin/bash

INTERVAL=$1

if [[ q$INTERVAL == 'q' ]]
then 
	echo $0 needs an interval argument
	echo e.g. "$0 30000"
	exit 1
fi

echo "Executing stopurms"
/home/sr99_ramp_metering/system/stopurms
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/sr99_ramp_metering/src/lnx/clt_vars &
sleep 1

TIMESTAMP=`date +%y%m%d_%H%M%S`


echo "Starting urmsgo with interval $INTERVAL"

/home/sr99_ramp_metering/system/urmsgo 10.253.28.96	3000	1004	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.25.116	3200	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.29.248.101	3400	1002	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.25.124	3600	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.102	3800	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.104	4000	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.103	4200 	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.27.67	4400 	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.27.82	4600 	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.27.81	4800 	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.105 	5000	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.28.213 	5200	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.28.212 	5400	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.127.2 	5600	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.107 	5800	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.106 	6000	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.24.156 	6200	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.24.157 	6400	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.26.183 	6600	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.110 	6800	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.29.248.81 	7000	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.108 	7200	1002	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.128 	7400	1003	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.128 	7600	1002	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.130 	7800	1002	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.26.103 	8000	1000	$TIMESTAMP $INTERVAL 
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.131 	8200	1000	$TIMESTAMP $INTERVAL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.253.28.134 	8400	1000	$TIMESTAMP $INTERVAL

cd /home/sr99_ramp_metering/src
mkdir Out_Data_$TIMESTAMP
rm Out_Data
ln -s Out_Data_$TIMESTAMP Out_Data
./lnx/opt_crm -i $INTERVAL >/big/data/ac_rm_1/opt_crm_$TIMESTAMP.txt &
