#!/bin/bash

echo "Executing stopurms"
/home/sr99_ramp_metering/system/stopurms
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/sr99_ramp_metering/src/lnx/clt_vars &
sleep 1

TIMESTAMP=`date +%y%m%d_%H%M%S`
INTERVAL=$1
CONTROL=$2

echo "Starting urmsgo with interval $INTERVAL control $CONTROL"

/home/sr99_ramp_metering/system/urmsgo 10.29.248.108	3000	1000	$TIMESTAMP $INTERVAL $CONTROL
#sleep 1
/home/sr99_ramp_metering/system/urmsgo 10.254.25.113	3200	1000	$TIMESTAMP $INTERVAL $CONTROL

cd /home/sr99_ramp_metering/src
mkdir Out_Data_$TIMESTAMP
ln -s Out_Data_$TIMESTAMP Out_Data
./lnx/opt_crm -i $INTERVAL >/dev/null &
